gitOps:
  namespace: openshift-gitops
#  source: redhat-operators
  source: cs-redhat-operator-index

gitRepoTemplate:
  # The URL of the repository setup in the Ansible step.
  url: git@<ip of host>:repos/ocp4-disconnected-config
  # The SSH key of the user that ran the Ansible step, used to connect to the git repo
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
