apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-day2
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: ./helm/openshift-gitops-day2
    repoURL: 
    targetRevision: HEAD
  syncPolicy:
    automated: {}
