{{- with .Values.mtv }}
# Brings in the operator group used for the nmstate operator.
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ForkliftController.v1beta1.forklift.konveyor.io,Hook.v1beta1.forklift.konveyor.io,Host.v1beta1.forklift.konveyor.io,Migration.v1beta1.forklift.konveyor.io,NetworkMap.v1beta1.forklift.konveyor.io,OpenStackVolumePopulator.v1beta1.forklift.konveyor.io,OvirtVolumePopulator.v1beta1.forklift.konveyor.io,Plan.v1beta1.forklift.konveyor.io,Provider.v1beta1.forklift.konveyor.io,StorageMap.v1beta1.forklift.konveyor.io
    argocd.argoproj.io/sync-wave: "2"
  name: {{ .target_namespace | default "openshift-mtv" }}
  namespace: {{ .target_namespace | default "openshift-mtv" }}
spec:
  targetNamespaces:
  - {{ .target_namespace | default "openshift-mtv" }}
  
  {{- end }}
