{{- with .Values.mtv }}

---

#Creates forklift controller instance for MTV.
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: {{ .target_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  controller_max_vm_inflight: {{ .controller_max_vm_inflight | default "20" }}
  feature_ui_plugin: 'true'
  feature_validation: 'true'
  feature_volume_populator: 'true'
{{- end -}}
