#!/usr/bin/ansible-playbook -K
- hosts: localhost
  gather_facts: true
  vars:
    common_content_pull: true
  roles:
    - role: ocp4.disconnected.mirror_content
      tags: push_cluster_images, stage_0
      vars:
        direction: pull
      when: 
        - common_content_pull | bool
        - common_connected_cluster is false

